server:
  port: 8762

spring:
  application:
    name: nasi-campur-localhost
  cloud:
    client:
      ipAddress: localhost

eureka:
  client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
