server:
  port: 8762

spring:
  application:
    name: nasi-campur-*
  cloud:
    client:
      ipAddress: ip 地址

eureka:
  client:
      serviceUrl:
        defaultZone: http://cdn.qfdk.me:8761/eureka/
  instance:
    ip-address: ip 地址
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}