server:
  port: 8762

spring:
  application:
    name: nasi-campur-localhost
  cloud:
    client:
      ipAddress: localhost
  security:
    user:
      name: user
      password: password

eureka:
  client:
      serviceUrl:
        defaultZone: http://user:pass@localhost:8761/eureka/
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
    ip-address: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS