server:
  port: 8762

spring:
  application:
    name: nasi-campur-cn1

eureka:
  client:
      serviceUrl:
        defaultZone: http://cdn.qfdk.me:8761/eureka/
  # 指定此实例的ip
    instance:
        ip-address: cn.qfdk.me
        # # 注册时使用ip而不是主机名
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}